import { Injectable } from '@nestjs/common'
import { NODE_CATALOG } from '@/standards/node-catalog.data'
import { normalizeFlowNode } from '@/iterations/normalize-node'
import type { FlowNodeDef } from '@/iterations/types/flow-node'

function xmlEscape(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function legacyRoleForKind(node: FlowNodeDef): string {
  switch (node.kind) {
    case 'TRIGGER': return 'TRIGGER'
    case 'GATEWAY': return 'GATEWAY'
    case 'TASK':
    default:
      // Legacy hint: if the node had a NodeCategory of AUTOMATIC keep it.
      return node.type === 'AUTOMATIC' ? 'AUTOMATIC' : 'MANUAL'
  }
}

@Injectable()
export class AmlExporterService {
  machineToAml(machine: any): string {
    const rawNodes = typeof machine.nodesJson === 'string' ? JSON.parse(machine.nodesJson) : machine.nodes ?? []
    const edges = typeof machine.edgesJson === 'string' ? JSON.parse(machine.edgesJson) : machine.edges ?? []

    const nodes: FlowNodeDef[] = rawNodes.map((n: any) => normalizeFlowNode(n))
    const nodeClasses = nodes.map((n) => this.nodeToSystemUnitClass(n)).join('\n')
    const internalElements = nodes.map((n) => this.nodeToInternalElement(n)).join('\n')
    const links = edges.map((e: any) => this.edgeToInternalLink(e)).join('\n')

    return `<?xml version="1.0" encoding="utf-8"?>
<CAEXFile SchemaVersion="3.0" FileName="${machine.name.replace(/\s+/g, '_')}.aml">
  <!-- Digital Thread Workflow: ${machine.name} v${machine.version} -->
  <!-- Generated by Digital Thread Backend -->

  <RoleClassLib Name="DigitalThreadRoles">
    <RoleClass Name="TRIGGER"><Description>Event-driven entry point</Description></RoleClass>
    <RoleClass Name="AUTOMATIC"><Description>Automated computational node</Description></RoleClass>
    <RoleClass Name="MANUAL"><Description>Human-executed activity</Description></RoleClass>
    <RoleClass Name="GATEWAY"><Description>Flow control gate (AND/OR/XOR)</Description></RoleClass>
    <RoleClass Name="STORAGE"><Description>Data persistence/export node</Description></RoleClass>
  </RoleClassLib>

  <InterfaceClassLib Name="DigitalThreadInterfaces">
    <InterfaceClass Name="FileInput"><Description>File input port</Description></InterfaceClass>
    <InterfaceClass Name="FileOutput"><Description>File output port</Description></InterfaceClass>
  </InterfaceClassLib>

  <SystemUnitClassLib Name="${machine.name.replace(/\s+/g, '_')}NodeTypes">
${nodeClasses}
  </SystemUnitClassLib>

  <InstanceHierarchy Name="${machine.name.replace(/\s+/g, '_')}Graph">
${internalElements}
${links}
  </InstanceHierarchy>

</CAEXFile>`
  }

  private nodeToSystemUnitClass(node: FlowNodeDef): string {
    const inputs = node.inputs ?? []
    const outputs = node.outputs ?? []
    const role = legacyRoleForKind(node)
    const displayName = node.name ?? node.label ?? node.id

    const inputInterfaces = inputs.map((inp) => {
      const src = inp.source
      const sourceDescriptor =
        src.kind === 'PREDECESSOR'
          ? `${src.kind}:${src.from.nodeId}.${src.from.outputId}`
          : src.kind === 'DATASOURCE'
            ? `${src.kind}:${src.dataSourceId}`
            : src.kind
      return `      <ExternalInterface Name="${xmlEscape(inp.id)}" RefBaseClassPath="DigitalThreadInterfaces/FileInput">
        <Attribute Name="name" AttributeDataType="xs:string" Value="${xmlEscape(inp.name ?? inp.id)}"/>
        <Attribute Name="source" AttributeDataType="xs:string" Value="${xmlEscape(sourceDescriptor)}"/>
        <Attribute Name="cardinality" AttributeDataType="xs:string" Value="${xmlEscape(inp.cardinality)}"/>
        <Attribute Name="required" AttributeDataType="xs:boolean" Value="${inp.required ? 'true' : 'false'}"/>
        <Attribute Name="fileTypes" AttributeDataType="xs:string" Value="${xmlEscape(JSON.stringify(inp.fileTypes ?? []))}"/>
      </ExternalInterface>`
    }).join('\n')

    const outputInterfaces = outputs.map((out) =>
      `      <ExternalInterface Name="${xmlEscape(out.id)}" RefBaseClassPath="DigitalThreadInterfaces/FileOutput">
        <Attribute Name="name" AttributeDataType="xs:string" Value="${xmlEscape(out.name ?? out.id)}"/>
        <Attribute Name="cardinality" AttributeDataType="xs:string" Value="${xmlEscape(out.cardinality)}"/>
        <Attribute Name="required" AttributeDataType="xs:boolean" Value="${out.required ? 'true' : 'false'}"/>
        <Attribute Name="fileTypes" AttributeDataType="xs:string" Value="${xmlEscape(JSON.stringify(out.fileTypes ?? []))}"/>
      </ExternalInterface>`
    ).join('\n')

    return `    <SystemUnitClass Name="${xmlEscape(node.id)}">
      <RoleRequirements RefBaseRoleClassPath="DigitalThreadRoles/${role}"/>
      <Attribute Name="kind" AttributeDataType="xs:string" Value="${xmlEscape(node.kind ?? 'TASK')}"/>
      <Attribute Name="name" AttributeDataType="xs:string" Value="${xmlEscape(displayName)}"/>
      <Attribute Name="description" AttributeDataType="xs:string" Value="${xmlEscape(node.description ?? '')}"/>
      <Attribute Name="tags" AttributeDataType="xs:string" Value="${xmlEscape(JSON.stringify(node.tags ?? []))}"/>
      <Attribute Name="responsiblePartnerId" AttributeDataType="xs:string" Value="${xmlEscape(node.responsiblePartnerId ?? '')}"/>
      <Attribute Name="responsiblePartnerIds" AttributeDataType="xs:string" Value="${xmlEscape(JSON.stringify(node.responsiblePartnerIds ?? []))}"/>
      <Attribute Name="responsiblePartner" AttributeDataType="xs:string" Value="${xmlEscape(node.responsiblePartner ?? '')}"/>
${inputInterfaces}
${outputInterfaces}
    </SystemUnitClass>`
  }

  private nodeToInternalElement(node: FlowNodeDef): string {
    return `    <InternalElement Name="${xmlEscape(node.id)}" RefBaseSystemUnitPath="${xmlEscape(node.id)}">
      <Attribute Name="positionX" AttributeDataType="xs:float" Value="${node.position?.x ?? 0}"/>
      <Attribute Name="positionY" AttributeDataType="xs:float" Value="${node.position?.y ?? 0}"/>
    </InternalElement>`
  }

  private edgeToInternalLink(edge: any): string {
    return `    <InternalLink Name="${xmlEscape(edge.id)}" RefPartnerSideA="${xmlEscape(edge.source)}" RefPartnerSideB="${xmlEscape(edge.target)}">${edge.label ? `\n      <Attribute Name="label" AttributeDataType="xs:string" Value="${xmlEscape(edge.label)}"/>` : ''}\n    </InternalLink>`
  }

  nodeCatalogToAml(): string {
    const classes = NODE_CATALOG.map((entry) => `    <SystemUnitClass Name="${entry.nodeTypeId}">
      <RoleRequirements RefBaseRoleClassPath="DigitalThreadRoles/${entry.category}"/>
      <Attribute Name="label" AttributeDataType="xs:string" Value="${entry.label}"/>
      <Attribute Name="color" AttributeDataType="xs:string" Value="${entry.color}"/>
      <Attribute Name="icon" AttributeDataType="xs:string" Value="${entry.icon ?? ''}"/>
      <Attribute Name="description" AttributeDataType="xs:string" Value="${(entry.description ?? '').replace(/"/g, '&quot;')}"/>
      <Attribute Name="defaultPartner" AttributeDataType="xs:string" Value="${entry.defaultPartner ?? ''}"/>
      <Attribute Name="expectedOutput" AttributeDataType="xs:string" Value="${entry.expectedOutput ?? ''}"/>
    </SystemUnitClass>`).join('\n')

    return `<?xml version="1.0" encoding="utf-8"?>
<CAEXFile SchemaVersion="3.0" FileName="DigitalThreadNodeCatalog.aml">
  <RoleClassLib Name="DigitalThreadRoles">
    <RoleClass Name="TRIGGER"/><RoleClass Name="AUTOMATIC"/>
    <RoleClass Name="MANUAL"/><RoleClass Name="GATEWAY"/><RoleClass Name="STORAGE"/>
  </RoleClassLib>
  <SystemUnitClassLib Name="DigitalThreadNodeCatalog">
${classes}
  </SystemUnitClassLib>
</CAEXFile>`
  }
}
