import { useEffect, useMemo, useState } from 'react'
import { useParams, useNavigate, useSearchParams, Link } from 'react-router-dom'
import { TopBar } from '@/components/layout/top-bar'
import { WipOverlay } from '@/components/common/wip-overlay'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  ArrowLeft,
  ArrowRight,
  ArrowLeftRight,
  GitBranch,
  FileText,
  X,
  Hash,
  Clock,
  Wrench,
  Lock,
  ExternalLink,
  Loader2,
  Layers,
  Users,
  PlayCircle,
} from 'lucide-react'
import {
  api,
  type LineageEdgeData,
  type LineageFileNode,
  type LineageGraphResponse,
  type LineagePartner,
  type LineageUsage,
} from '@/lib/api'
import {
  ReactFlow,
  Background,
  Controls,
  MarkerType,
  Handle,
  Position,
  type Edge,
  type Node,
  type NodeTypes,
} from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { cn } from '@/lib/utils'
import { useDownloadOrRequest } from '@/hooks/use-download-or-request'
import { RequestAccessDialog } from '@/components/governance/request-access-dialog'
import { FileDownloadButton } from '@/components/governance/file-download-button'
import { useAuthStore } from '@/stores/auth-store'

// ─── Types (frontend-local aliases) ─────────────────────────────────────────

type LineageFile = LineageFileNode
type LineageEdgeRaw = LineageEdgeData
type LineageGraph = LineageGraphResponse
type ViewMode = 'files' | 'iterations'

// ─── Style maps ─────────────────────────────────────────────────────────────

const CLASS_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  PUBLIC:       { bg: 'bg-blue-500/10',    text: 'text-blue-300',    border: 'border-blue-500/30' },
  INTERNAL:     { bg: 'bg-slate-500/10',   text: 'text-slate-300',   border: 'border-slate-500/30' },
  PARTNER:      { bg: 'bg-violet-500/10',  text: 'text-violet-300',  border: 'border-violet-500/30' },
  CONFIDENTIAL: { bg: 'bg-amber-500/10',   text: 'text-amber-300',   border: 'border-amber-500/30' },
  RESTRICTED:   { bg: 'bg-red-500/10',     text: 'text-red-300',     border: 'border-red-500/30' },
}

/**
 * Friendlier label per W3C PROV-O relation type - the raw constants
 * (`WAS_DERIVED_FROM` etc.) are jargon for non-experts. The tooltip on each
 * edge still includes the raw relation name for SUPERADMIN/OWNER auditors.
 */
const REL_LABEL: Record<string, string> = {
  WAS_DERIVED_FROM: 'derived from',
  WAS_GENERATED_BY: 'generated by',
  USED: 'used',
  WAS_REVISION_OF: 'revision of',
  // Synthetic aggregation label in Group-by-iteration view: "iteration A produced
  // files that iteration B consumed as input" - surfaces cross-iteration usage
  // even when no downstream files were derived in the consumer.
  USES: 'uses files from',
}

// ─── Layout helpers ──────────────────────────────────────────────────────────

/**
 * Assign each node a (depth, slot) coordinate.
 *  - root sits at depth 0
 *  - upstream ancestors get negative depth
 *  - downstream descendants get positive depth
 * Within a column, nodes from the same iteration are grouped together so
 * cross-iteration clusters read as visual blocks.
 */
function layoutByDepth<TItem extends { id: string; iterationId?: string | null; filename?: string }>(
  rootId: string,
  items: TItem[],
  edges: Array<{ source: string; target: string }>,
  opts: { colWidth: number; rowHeight: number },
) {
  const depth = new Map<string, number>()
  depth.set(rootId, 0)

  const childrenOf = new Map<string, Set<string>>()
  const parentsOf = new Map<string, Set<string>>()
  for (const e of edges) {
    if (!childrenOf.has(e.source)) childrenOf.set(e.source, new Set())
    childrenOf.get(e.source)!.add(e.target)
    if (!parentsOf.has(e.target)) parentsOf.set(e.target, new Set())
    parentsOf.get(e.target)!.add(e.source)
  }

  const dq: string[] = [rootId]
  while (dq.length) {
    const id = dq.shift()!
    const d = depth.get(id)!
    for (const c of childrenOf.get(id) ?? []) {
      const cur = depth.get(c)
      const nd = d + 1
      if (cur === undefined || nd > cur) {
        depth.set(c, nd)
        dq.push(c)
      }
    }
  }
  const uq: string[] = [rootId]
  while (uq.length) {
    const id = uq.shift()!
    const d = depth.get(id)!
    for (const p of parentsOf.get(id) ?? []) {
      const cur = depth.get(p)
      const nd = d - 1
      if (cur === undefined || nd < cur) {
        depth.set(p, nd)
        uq.push(p)
      }
    }
  }

  const byDepth = new Map<number, TItem[]>()
  for (const n of items) {
    const d = depth.get(n.id) ?? 99
    if (!byDepth.has(d)) byDepth.set(d, [])
    byDepth.get(d)!.push(n)
  }
  // Sort within each column by iterationId (so same-iteration nodes cluster
  // visually) then by filename for stability.
  for (const list of byDepth.values()) {
    list.sort((a, b) => {
      const ai = a.iterationId ?? ''
      const bi = b.iterationId ?? ''
      if (ai !== bi) return ai.localeCompare(bi)
      return (a.filename ?? '').localeCompare(b.filename ?? '')
    })
  }

  const positions = new Map<string, { x: number; y: number }>()
  for (const [d, list] of byDepth) {
    const colHeight = list.length * opts.rowHeight
    const yStart = -colHeight / 2 + opts.rowHeight / 2
    list.forEach((it, idx) => {
      positions.set(it.id, { x: d * opts.colWidth, y: yStart + idx * opts.rowHeight })
    })
  }
  return { positions, depth }
}

// ─── File-level node (default view) ──────────────────────────────────────────

interface FileNodeData extends Record<string, unknown> {
  file: LineageFile
  isRoot: boolean
  depth: number
  selected?: boolean
  onSelect: (id: string) => void
}

function FileLineageNode({ data }: { data: FileNodeData }) {
  const { file, isRoot, depth, selected, onSelect } = data
  const cls = CLASS_COLORS[file.classification ?? 'INTERNAL'] ?? CLASS_COLORS.INTERNAL
  const isUpstream = depth < 0
  const isDownstream = depth > 0
  const sizeKb = typeof file.sizeBytes === 'number' ? (file.sizeBytes / 1024).toFixed(1) : null
  // Border color follows the partner so two files from the same partner read
  // as visually grouped without needing to read labels. Falls back to a root
  // accent or neutral slate.
  const accent = file.partner?.color ?? (isRoot ? '#60a5fa' : '#475569')

  return (
    <div
      className={cn(
        'rounded-md border bg-card/95 text-foreground shadow-md w-[252px] cursor-pointer transition-all',
        isRoot && 'ring-2 ring-blue-400',
        selected && !isRoot && 'ring-2 ring-emerald-400',
        !isRoot && !selected && 'hover:border-foreground/30',
      )}
      style={{ borderColor: accent }}
      onClick={(e) => { e.stopPropagation(); onSelect(file.id) }}
      title={file.filename}
    >
      <Handle type="target" position={Position.Left} className="!w-2 !h-2 !bg-slate-500" />

      {/* Iteration ribbon - the headline piece of cross-iteration context.
          Tinted to the partner color so two files from the same iteration
          are visually obvious. A "+N" pill flags when the file is also used
          in additional iterations beyond the one that produced it. */}
      <div
        className="px-2.5 py-1 flex items-center justify-between gap-1 text-[10px] font-medium border-b"
        style={{
          background: file.partner ? `${file.partner.color}22` : 'rgba(100,116,139,0.12)',
          borderColor: file.partner ? `${file.partner.color}55` : 'rgba(100,116,139,0.3)',
          color: file.partner?.color ?? '#94a3b8',
        }}
      >
        <span className="inline-flex items-center gap-1 truncate" title={file.iterationDisplayId ?? file.iterationId}>
          <PlayCircle className="h-2.5 w-2.5 shrink-0" aria-hidden="true" />
          <span className="font-mono truncate">{file.iterationDisplayId ?? file.iterationId.slice(0, 8) + '…'}</span>
        </span>
        <span className="inline-flex items-center gap-1 shrink-0">
          {(() => {
            const otherIters = new Set(
              file.usages.map((u) => u.iterationId).filter((id) => id !== file.iterationId),
            )
            if (otherIters.size === 0) return null
            return (
              <span
                className="inline-flex items-center gap-0.5 px-1 py-0 rounded text-[8px] font-semibold border border-amber-500/50 bg-amber-500/15 text-amber-300"
                title={`Also used as input in ${otherIters.size} other iteration${otherIters.size === 1 ? '' : 's'}`}
              >
                +{otherIters.size} iter
              </span>
            )
          })()}
          {file.partner && (
            <span className="inline-flex items-center gap-0.5">
              <span className="inline-block w-1.5 h-1.5 rounded-full" style={{ background: file.partner.color }} />
              {file.partner.code}
            </span>
          )}
        </span>
      </div>

      <div className="px-2.5 py-2 space-y-1.5">
        <div className="flex items-start gap-1.5">
          <FileText className={cn('h-3.5 w-3.5 mt-0.5 shrink-0', isRoot ? 'text-blue-400' : 'text-muted-foreground')} aria-hidden="true" />
          <div className="min-w-0 flex-1">
            <p className="text-[11px] font-semibold truncate" title={file.filename}>{file.filename}</p>
            <p className="text-[9px] text-muted-foreground font-mono truncate" title={file.id}>
              {file.id.slice(0, 8)}…
            </p>
          </div>
        </div>
        <div className="flex items-center gap-1 flex-wrap">
          <span
            className={cn(
              'text-[8px] font-semibold uppercase tracking-wide rounded px-1.5 py-0.5 border',
              cls.bg, cls.text, cls.border,
            )}
          >
            <Lock className="h-2 w-2 inline mr-0.5" aria-hidden="true" />
            {file.classification ?? 'INTERNAL'}
          </span>
          {isRoot && <Badge variant="outline" className="text-[8px] h-3.5 px-1 leading-none border-blue-500/50 text-blue-300">root</Badge>}
          {isUpstream && <Badge variant="outline" className="text-[8px] h-3.5 px-1 leading-none">upstream · d{Math.abs(depth)}</Badge>}
          {isDownstream && <Badge variant="outline" className="text-[8px] h-3.5 px-1 leading-none">downstream · d{depth}</Badge>}
        </div>
        {file.nodeSourceLabel && (
          <p className="text-[9px] text-muted-foreground truncate">
            from <span className="font-mono">{file.nodeSourceLabel}</span>
          </p>
        )}
        {sizeKb && (
          <p className="text-[9px] text-muted-foreground/80 tabular-nums">{sizeKb} KB</p>
        )}
      </div>
      <Handle type="source" position={Position.Right} className="!w-2 !h-2 !bg-slate-500" />
    </div>
  )
}

// ─── Iteration super-node (Group-by-iteration view) ─────────────────────────

interface IterationGroup {
  id: string
  iterationId: string
  iterationDisplayId: string | null
  iterationStatus: string | null
  iterationMachineName: string | null
  iterationCreatedAt: string | null
  /** Files produced in this iteration that touch the lineage chain. */
  files: LineageFile[]
  /** Files produced in OTHER iterations that this iteration consumes as input. */
  referencedFiles: LineageFile[]
  partners: LineagePartner[]
  /** True when this group's only relationship to the chain is "uses" (no produced files). */
  isReferenceOnly: boolean
  // mirrors layoutByDepth's TItem.filename so the same fn handles both modes
  filename?: string
}

interface IterationNodeData extends Record<string, unknown> {
  group: IterationGroup
  containsRoot: boolean
  rootFileId: string
  selected?: boolean
  onSelect: (id: string) => void
}

function IterationGroupNode({ data }: { data: IterationNodeData }) {
  const { group, containsRoot, selected, onSelect } = data
  const accent = group.partners[0]?.color ?? '#60a5fa'
  return (
    <div
      className={cn(
        'rounded-md border-2 bg-card/95 shadow-md w-[280px] cursor-pointer transition-all',
        containsRoot && 'ring-2 ring-blue-400',
        selected && !containsRoot && 'ring-2 ring-emerald-400',
        group.isReferenceOnly && 'border-dashed opacity-90',
      )}
      style={{ borderColor: accent }}
      onClick={(e) => { e.stopPropagation(); onSelect(group.id) }}
      title={group.iterationDisplayId ?? group.iterationId}
    >
      <Handle type="target" position={Position.Left} className="!w-2 !h-2 !bg-slate-500" />
      <div
        className="px-3 py-1.5 flex items-center justify-between gap-2 text-[11px] font-semibold border-b"
        style={{ background: `${accent}26`, borderColor: `${accent}66`, color: accent }}
      >
        <span className="inline-flex items-center gap-1.5 truncate">
          <PlayCircle className="h-3 w-3 shrink-0" />
          <span className="font-mono truncate">{group.iterationDisplayId ?? group.iterationId.slice(0, 8) + '…'}</span>
        </span>
        {containsRoot && <Badge variant="outline" className="text-[8px] h-3.5 px-1 leading-none border-blue-500/50 text-blue-300">root</Badge>}
      </div>
      <div className="px-3 py-2 space-y-1.5">
        <p className="text-[11px] font-medium truncate" title={group.iterationMachineName ?? ''}>
          {group.iterationMachineName ?? 'Unknown workflow'}
        </p>
        <div className="flex items-center gap-1 flex-wrap">
          {group.iterationStatus && (
            <Badge variant="outline" className="text-[9px] h-3.5 px-1 leading-none">
              {group.iterationStatus}
            </Badge>
          )}
          {group.files.length > 0 && (
            <Badge variant="outline" className="text-[9px] h-3.5 px-1 leading-none">
              <FileText className="h-2 w-2 mr-0.5" /> {group.files.length} produced
            </Badge>
          )}
          {group.referencedFiles.length > 0 && (
            <Badge
              variant="outline"
              className="text-[9px] h-3.5 px-1 leading-none border-amber-500/50 text-amber-300 bg-amber-500/10"
              title="Files produced in other iterations that this iteration consumed as input"
            >
              <ArrowLeft className="h-2 w-2 mr-0.5" /> {group.referencedFiles.length} used
            </Badge>
          )}
          {group.isReferenceOnly && (
            <Badge variant="outline" className="text-[9px] h-3.5 px-1 leading-none border-amber-500/50 text-amber-300">
              consumer only
            </Badge>
          )}
        </div>
        {group.partners.length > 0 && (
          <div className="flex items-center gap-1 flex-wrap">
            {group.partners.map((p) => (
              <span
                key={p.id}
                className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[9px] border"
                style={{ background: `${p.color}1a`, borderColor: `${p.color}55`, color: p.color }}
                title={p.fullName}
              >
                <span className="inline-block w-1.5 h-1.5 rounded-full" style={{ background: p.color }} />
                {p.code}
              </span>
            ))}
          </div>
        )}
        <p className="text-[9px] text-muted-foreground/80 italic">
          Click to inspect files; double-click to open iteration.
        </p>
      </div>
      <Handle type="source" position={Position.Right} className="!w-2 !h-2 !bg-slate-500" />
    </div>
  )
}

const nodeTypes: NodeTypes = {
  fileLineage: FileLineageNode,
  iterationLineage: IterationGroupNode,
}

// ─── Page ────────────────────────────────────────────────────────────────────

export function LineageExplorer() {
  const { fileId } = useParams<{ fileId: string }>()
  const [params] = useSearchParams()
  const depthParam = Number(params.get('depth') ?? '5')
  const navigate = useNavigate()
  const [graph, setGraph] = useState<LineageGraph | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [selectedFileId, setSelectedFileId] = useState<string | null>(null)
  const [selectedGroupId, setSelectedGroupId] = useState<string | null>(null)
  const [hoveredEdge, setHoveredEdge] = useState<LineageEdgeRaw | null>(null)
  const [viewMode, setViewMode] = useState<ViewMode>('files')

  useEffect(() => {
    if (!fileId) return
    setLoading(true)
    setError(null)
    api.lineage
      .full(fileId, depthParam)
      .then((g) => {
        setGraph(g)
        setSelectedFileId(g.root)
        setSelectedGroupId(null)
      })
      .catch((e: any) => setError(e?.message ?? 'Failed to load lineage'))
      .finally(() => setLoading(false))
  }, [fileId, depthParam])

  // ── Scope summary (iterations + partners involved) ────────────────────────
  // "Iterations involved" counts BOTH producing iterations and any iteration
  // that consumes a file in the chain as INPUT - matches what the Thread
  // Explorer "references" view shows.
  const scope = useMemo(() => {
    if (!graph) return null
    const producingIters = new Set<string>()
    const consumingIters = new Set<string>()
    const partnerById = new Map<string, LineagePartner>()
    let earliest: Date | null = null
    let latest: Date | null = null
    for (const f of graph.nodes) {
      if (f.iterationId) producingIters.add(f.iterationId)
      if (f.partner) partnerById.set(f.partner.id, f.partner)
      if (f.timestamp) {
        const t = new Date(f.timestamp)
        if (!earliest || t < earliest) earliest = t
        if (!latest || t > latest) latest = t
      }
      for (const u of f.usages) {
        if (u.role === 'INPUT' && u.iterationId !== f.iterationId) consumingIters.add(u.iterationId)
      }
    }
    const totalIters = new Set<string>([...producingIters, ...consumingIters])
    return {
      iterationCount: totalIters.size,
      producingCount: producingIters.size,
      consumingOnlyCount: Array.from(consumingIters).filter((id) => !producingIters.has(id)).length,
      partners: Array.from(partnerById.values()),
      earliest,
      latest,
    }
  }, [graph])

  // ── Iteration groups (super-nodes for "Group by iteration" mode) ──────────
  //
  // Three sources of iteration nodes:
  //   1) Iterations that PRODUCED files in the lineage chain (the "owning" iterationId
  //      of any file in graph.nodes).
  //   2) Iterations that REFERENCE those files as INPUT (from file.usages with role=INPUT).
  //      These were missing before - a file used as input in iteration B but produced in
  //      iteration A would only show A in the cluster view, even though the File Explorer
  //      correctly lists both. Without this, the bug the user reported persists in Group mode.
  //   3) Edges between groups come from two sources:
  //        a) real LineageEdge rows whose endpoints land in two different groups
  //        b) synthetic "uses" edges: iteration B referencing a file produced in iteration A
  //           gets a synthetic A → B edge labelled "uses". These are aggregated by relation type.
  const { iterationGroups, groupEdges, fileToGroup } = useMemo(() => {
    if (!graph) {
      return {
        iterationGroups: [] as IterationGroup[],
        groupEdges: [] as Array<LineageEdgeRaw & { count: number }>,
        fileToGroup: new Map<string, string>(),
      }
    }

    type AggEdge = LineageEdgeRaw & { count: number }
    const groupsByIter = new Map<string, IterationGroup>()

    const ensureGroup = (
      iterationId: string,
      meta: Partial<Pick<IterationGroup, 'iterationDisplayId' | 'iterationStatus' | 'iterationMachineName' | 'iterationCreatedAt'>>,
    ): IterationGroup => {
      let g = groupsByIter.get(iterationId)
      if (g) {
        // Backfill richer metadata if a later file in this iteration carries it.
        if (!g.iterationDisplayId && meta.iterationDisplayId) g.iterationDisplayId = meta.iterationDisplayId
        if (!g.iterationStatus && meta.iterationStatus) g.iterationStatus = meta.iterationStatus
        if (!g.iterationMachineName && meta.iterationMachineName) g.iterationMachineName = meta.iterationMachineName
        if (!g.iterationCreatedAt && meta.iterationCreatedAt) g.iterationCreatedAt = meta.iterationCreatedAt
        return g
      }
      g = {
        id: `iter:${iterationId}`,
        iterationId,
        iterationDisplayId: meta.iterationDisplayId ?? null,
        iterationStatus: meta.iterationStatus ?? null,
        iterationMachineName: meta.iterationMachineName ?? null,
        iterationCreatedAt: meta.iterationCreatedAt ?? null,
        files: [],
        referencedFiles: [],
        partners: [],
        isReferenceOnly: true, // flipped to false once a produced file lands here
      }
      groupsByIter.set(iterationId, g)
      return g
    }

    // 1) Producing iterations.
    for (const f of graph.nodes) {
      const g = ensureGroup(f.iterationId, {
        iterationDisplayId: f.iterationDisplayId,
        iterationStatus: f.iterationStatus,
        iterationMachineName: f.iterationMachineName,
        iterationCreatedAt: f.iterationCreatedAt,
      })
      g.files.push(f)
      g.isReferenceOnly = false
      if (f.partner && !g.partners.find((p) => p.id === f.partner!.id)) g.partners.push(f.partner)
    }

    // 2) Consuming-only iterations from each file's usages.
    for (const f of graph.nodes) {
      for (const u of f.usages) {
        if (u.role !== 'INPUT') continue
        if (u.iterationId === f.iterationId) continue
        const g = ensureGroup(u.iterationId, {
          iterationDisplayId: u.iterationDisplayId,
          iterationStatus: u.iterationStatus,
        })
        if (!g.referencedFiles.find((rf) => rf.id === f.id)) g.referencedFiles.push(f)
        if (f.partner && !g.partners.find((p) => p.id === f.partner!.id)) g.partners.push(f.partner)
      }
    }

    const fileToGroup = new Map<string, string>()
    for (const g of groupsByIter.values()) {
      g.filename = g.iterationDisplayId ?? g.iterationId
      for (const f of g.files) fileToGroup.set(f.id, g.id)
    }

    // 3a) Real edges between groups (file→file lineage spanning iterations).
    const byKey = new Map<string, AggEdge>()
    for (const e of graph.edges) {
      const sg = fileToGroup.get(e.source)
      const tg = fileToGroup.get(e.target)
      if (!sg || !tg || sg === tg) continue
      const key = `${sg}->${tg}:${e.relationType}`
      const existing = byKey.get(key)
      if (existing) {
        existing.count++
      } else {
        byKey.set(key, { ...e, id: key, source: sg, target: tg, count: 1 })
      }
    }

    // 3b) Synthetic "uses" edges: producing iteration → consuming iteration.
    // This is what surfaces the previously-hidden second-iteration usage of a
    // file. Aggregated by (producing iter, consuming iter) regardless of how
    // many individual files cross.
    for (const f of graph.nodes) {
      const producerGroup = fileToGroup.get(f.id)
      if (!producerGroup) continue
      for (const u of f.usages) {
        if (u.role !== 'INPUT') continue
        if (u.iterationId === f.iterationId) continue
        const consumerGroupId = `iter:${u.iterationId}`
        const key = `${producerGroup}->${consumerGroupId}:USES`
        const existing = byKey.get(key)
        if (existing) {
          existing.count++
        } else {
          byKey.set(key, {
            id: key,
            source: producerGroup,
            target: consumerGroupId,
            relationType: 'USES',
            count: 1,
          } as AggEdge)
        }
      }
    }

    return {
      iterationGroups: Array.from(groupsByIter.values()),
      groupEdges: Array.from(byKey.values()),
      fileToGroup,
    }
  }, [graph])

  // ── XYFlow nodes + edges for the active view mode ─────────────────────────
  const { rfNodes, rfEdges, depthByNode } = useMemo(() => {
    if (!graph) return { rfNodes: [] as Node[], rfEdges: [] as Edge[], depthByNode: new Map<string, number>() }

    if (viewMode === 'files') {
      const { positions, depth } = layoutByDepth(graph.root, graph.nodes, graph.edges, { colWidth: 290, rowHeight: 140 })
      const rfNodes: Node[] = graph.nodes.map((n) => ({
        id: n.id,
        type: 'fileLineage',
        position: positions.get(n.id) ?? { x: 0, y: 0 },
        data: {
          file: n,
          isRoot: n.id === graph.root,
          depth: depth.get(n.id) ?? 0,
          selected: n.id === selectedFileId,
          onSelect: setSelectedFileId,
        } satisfies FileNodeData,
        draggable: true,
      }))
      const rfEdges: Edge[] = graph.edges.map((e) => ({
        id: e.id,
        source: e.source,
        target: e.target,
        label: REL_LABEL[e.relationType] ?? e.relationType.toLowerCase().replace(/_/g, ' '),
        labelStyle: { fontSize: 9, fill: '#9ca3af' },
        labelBgStyle: { fill: '#1f2937', fillOpacity: 0.85 },
        labelBgPadding: [3, 2] as [number, number],
        labelBgBorderRadius: 4,
        markerEnd: { type: MarkerType.ArrowClosed, color: '#60a5fa' },
        style: { stroke: '#60a5fa', strokeWidth: 1.5 },
        data: e as unknown as Record<string, unknown>,
      }))
      return { rfNodes, rfEdges, depthByNode: depth }
    }

    // Iterations view: super-nodes per iteration + aggregated edges.
    const rootGroupId = fileToGroup.get(graph.root) ?? iterationGroups[0]?.id ?? ''
    const { positions, depth } = layoutByDepth(
      rootGroupId,
      iterationGroups,
      groupEdges,
      { colWidth: 340, rowHeight: 170 },
    )
    const rfNodes: Node[] = iterationGroups.map((g) => ({
      id: g.id,
      type: 'iterationLineage',
      position: positions.get(g.id) ?? { x: 0, y: 0 },
      data: {
        group: g,
        containsRoot: g.files.some((f) => f.id === graph.root),
        rootFileId: graph.root,
        selected: g.id === selectedGroupId,
        onSelect: setSelectedGroupId,
      } satisfies IterationNodeData,
      draggable: true,
    }))
    const rfEdges: Edge[] = groupEdges.map((e) => {
      const isUses = e.relationType === 'USES'
      // Synthetic "uses" edges (cross-iteration input references) get an
      // amber tint to read distinctly from real derivation edges.
      const stroke = isUses ? '#fbbf24' : '#60a5fa'
      return {
        id: e.id,
        source: e.source,
        target: e.target,
        label: `${e.count} ${REL_LABEL[e.relationType] ?? 'derivations'}`,
        labelStyle: { fontSize: 10, fill: isUses ? '#fcd34d' : '#cbd5e1' },
        labelBgStyle: { fill: '#1f2937', fillOpacity: 0.9 },
        labelBgPadding: [4, 3] as [number, number],
        labelBgBorderRadius: 4,
        markerEnd: { type: MarkerType.ArrowClosed, color: stroke },
        style: {
          stroke,
          strokeWidth: 1.5 + Math.min(3, Math.log2(e.count + 1)),
          strokeDasharray: isUses ? '5 3' : undefined,
        },
        data: e as unknown as Record<string, unknown>,
      }
    })
    return { rfNodes, rfEdges, depthByNode: depth }
  }, [graph, viewMode, selectedFileId, selectedGroupId, iterationGroups, groupEdges, fileToGroup])

  const selectedFile = useMemo(() => {
    if (!graph || !selectedFileId) return null
    return graph.nodes.find((n) => n.id === selectedFileId) ?? null
  }, [graph, selectedFileId])

  const selectedGroup = useMemo(() => {
    if (!selectedGroupId) return null
    return iterationGroups.find((g) => g.id === selectedGroupId) ?? null
  }, [iterationGroups, selectedGroupId])

  const incomingEdgesForSelected = useMemo(() => {
    if (!graph || !selectedFileId) return [] as LineageEdgeRaw[]
    return graph.edges.filter((e) => e.target === selectedFileId)
  }, [graph, selectedFileId])
  const outgoingEdgesForSelected = useMemo(() => {
    if (!graph || !selectedFileId) return [] as LineageEdgeRaw[]
    return graph.edges.filter((e) => e.source === selectedFileId)
  }, [graph, selectedFileId])

  return (
    <WipOverlay>
      <TopBar
        title="Lineage Explorer"
        subtitle="Where this file comes from and where it goes - across iterations and partners"
        actions={
          <Button variant="ghost" size="sm" onClick={() => navigate(-1)}>
            <ArrowLeft className="h-4 w-4 mr-1" /> Back
          </Button>
        }
      />
      <div className="p-6 space-y-4">
        {/* Scope summary - the one-glance "what am I looking at" card */}
        {scope && graph && (
          <ScopeSummary
            scope={scope}
            graph={graph}
            depthLimit={depthParam}
            viewMode={viewMode}
            onViewModeChange={setViewMode}
          />
        )}

        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2 flex-wrap">
              <GitBranch className="h-4 w-4" />
              {viewMode === 'files' ? 'File-to-file derivation' : 'Iteration-to-iteration derivation'}
              {graph && viewMode === 'files' && (
                <>
                  <Badge variant="outline" className="text-[10px]">{graph.nodes.length} file(s)</Badge>
                  <Badge variant="outline" className="text-[10px]">{graph.edges.length} edge(s)</Badge>
                </>
              )}
              {graph && viewMode === 'iterations' && (
                <>
                  <Badge variant="outline" className="text-[10px]">{iterationGroups.length} iteration(s)</Badge>
                  <Badge variant="outline" className="text-[10px]">{groupEdges.length} cross-iter edge(s)</Badge>
                </>
              )}
            </CardTitle>
            <p className="text-[10px] text-muted-foreground mt-1">
              {viewMode === 'files'
                ? 'Each node is one file; the arrow goes from the upstream file to the downstream file. Click a node to inspect it; double-click to open the iteration that produced it.'
                : 'Each box is one iteration; the arrow means "files produced in this iteration were used to produce files in that iteration". The number on the arrow is how many file-to-file derivations it aggregates. Click to inspect; double-click to open the iteration.'}
            </p>
          </CardHeader>
          <CardContent className="p-0">
            {loading && (
              <div className="flex items-center gap-2 p-6 text-sm text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" /> Loading lineage…
              </div>
            )}
            {error && <div className="p-4 text-sm text-red-400">{error}</div>}
            {!loading && !error && graph && (
              <div className="flex">
                {/* Graph */}
                <div className="relative flex-1 h-[600px] border-r border-border">
                  {graph.nodes.length === 1 ? (
                    <div className="p-6 text-sm text-muted-foreground">
                      No lineage edges recorded for this file yet. Run "Rebuild lineage" from the iteration page
                      if you expected derivation.
                    </div>
                  ) : (
                    <>
                      <ReactFlow
                        nodes={rfNodes}
                        edges={rfEdges}
                        nodeTypes={nodeTypes}
                        fitView
                        nodesDraggable
                        nodesConnectable={false}
                        elementsSelectable
                        onEdgeMouseEnter={(_, edge) => setHoveredEdge(edge.data as unknown as LineageEdgeRaw)}
                        onEdgeMouseLeave={() => setHoveredEdge(null)}
                        onPaneClick={() => {
                          if (viewMode === 'files') setSelectedFileId(graph.root)
                          else setSelectedGroupId(null)
                        }}
                        onNodeDoubleClick={(_, node) => {
                          if (viewMode === 'iterations') {
                            const g = iterationGroups.find((x) => x.id === node.id)
                            if (g) navigate(`/iteration/${g.iterationId}`)
                          } else {
                            const f = graph.nodes.find((x) => x.id === node.id)
                            if (f?.iterationId) navigate(`/iteration/${f.iterationId}`)
                          }
                        }}
                        proOptions={{ hideAttribution: true }}
                      >
                        <Background />
                        <Controls showInteractive={false} />
                      </ReactFlow>

                      {/* Depth banner overlay (legend on top edge) */}
                      <div className="pointer-events-none absolute inset-x-0 top-2 px-3 flex items-center justify-between text-[10px] text-muted-foreground">
                        <span className="inline-flex items-center gap-1 rounded bg-card/80 border border-border px-1.5 py-0.5">
                          <ArrowLeft className="h-3 w-3 text-red-400" /> Upstream (origins)
                        </span>
                        <span className="inline-flex items-center gap-1 rounded bg-blue-500/15 border border-blue-500/40 text-blue-300 px-1.5 py-0.5">
                          <ArrowLeftRight className="h-3 w-3" /> Root file
                        </span>
                        <span className="inline-flex items-center gap-1 rounded bg-card/80 border border-border px-1.5 py-0.5">
                          Downstream (consumers) <ArrowRight className="h-3 w-3 text-emerald-400" />
                        </span>
                      </div>

                      {/* Edge tooltip - fixed bottom-left when hovering an edge */}
                      {hoveredEdge && (
                        <div className="absolute bottom-3 left-3 max-w-md rounded-md border border-border bg-card/95 p-2.5 text-[11px] shadow-lg">
                          <div className="flex items-center gap-1.5 mb-1">
                            <GitBranch className="h-3 w-3 text-blue-400" />
                            <span className="font-semibold">
                              {REL_LABEL[hoveredEdge.relationType] ?? hoveredEdge.relationType}
                            </span>
                            <span className="text-[9px] text-muted-foreground font-mono">
                              ({hoveredEdge.relationType})
                            </span>
                          </div>
                          {hoveredEdge.transformInfo?.handlerName && (
                            <p className="text-[10px] text-muted-foreground">
                              <Wrench className="inline h-2.5 w-2.5 mr-0.5" />
                              produced by handler <code className="font-mono">{hoveredEdge.transformInfo.handlerName}</code>
                              {hoveredEdge.transformInfo.handlerVersion ? ` v${hoveredEdge.transformInfo.handlerVersion}` : ''}
                            </p>
                          )}
                          {hoveredEdge.createdAt && (
                            <p className="text-[10px] text-muted-foreground">
                              <Clock className="inline h-2.5 w-2.5 mr-0.5" />
                              recorded {new Date(hoveredEdge.createdAt).toLocaleString()}
                            </p>
                          )}
                        </div>
                      )}
                    </>
                  )}
                </div>

                {/* Side panel - metadata of the selected file / iteration cluster */}
                <aside className="w-[340px] shrink-0 p-3 overflow-y-auto h-[600px]">
                  {viewMode === 'iterations' && selectedGroup ? (
                    <IterationPanel
                      group={selectedGroup}
                      isRootGroup={selectedGroup.files.some((f) => f.id === graph.root)}
                      onPickFile={(fid) => {
                        setViewMode('files')
                        setSelectedFileId(fid)
                      }}
                      navigate={navigate}
                    />
                  ) : viewMode === 'iterations' ? (
                    <p className="text-[11px] text-muted-foreground italic">
                      Click an iteration box to see the files it contributed to this lineage chain.
                    </p>
                  ) : selectedFile ? (
                    <SelectedPanel
                      file={selectedFile}
                      depth={depthByNode.get(selectedFile.id) ?? 0}
                      isRoot={selectedFile.id === graph.root}
                      incoming={incomingEdgesForSelected}
                      outgoing={outgoingEdgesForSelected}
                      navigate={navigate}
                      clearSelection={() => setSelectedFileId(graph.root)}
                      allNodes={graph.nodes}
                    />
                  ) : (
                    <p className="text-[11px] text-muted-foreground italic">Click a node to inspect it.</p>
                  )}
                </aside>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </WipOverlay>
  )
}

// ─── Scope summary ───────────────────────────────────────────────────────────

function ScopeSummary({
  scope,
  graph,
  depthLimit,
  viewMode,
  onViewModeChange,
}: {
  scope: {
    iterationCount: number
    producingCount: number
    consumingOnlyCount: number
    partners: LineagePartner[]
    earliest: Date | null
    latest: Date | null
  }
  graph: LineageGraph
  depthLimit: number
  viewMode: ViewMode
  onViewModeChange: (m: ViewMode) => void
}) {
  const rootFile = graph.nodes.find((n) => n.id === graph.root)
  const span = scope.earliest && scope.latest ? scope.latest.getTime() - scope.earliest.getTime() : 0
  const spanLabel = span > 0 ? fmtSpan(span) : null

  return (
    <Card>
      <CardContent className="p-3 space-y-3">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3 text-xs">
          <SummaryStat
            icon={<FileText className="h-3 w-3" />}
            label="Files in chain"
            value={graph.nodes.length.toLocaleString()}
            sub={`${graph.edges.length} derivation${graph.edges.length === 1 ? '' : 's'}, depth ≤ ${depthLimit}`}
          />
          <SummaryStat
            icon={<PlayCircle className="h-3 w-3" />}
            label="Iterations involved"
            value={scope.iterationCount.toLocaleString()}
            sub={
              scope.iterationCount === 1
                ? 'all files from one run'
                : scope.consumingOnlyCount > 0
                ? `${scope.producingCount} produced files, ${scope.consumingOnlyCount} only consumed`
                : 'spanning multiple runs'
            }
          />
          <SummaryStat
            icon={<Users className="h-3 w-3" />}
            label="Partners involved"
            value={scope.partners.length.toLocaleString()}
            sub={scope.partners.map((p) => p.code).join(' · ') || 'no partner attribution'}
          />
          <SummaryStat
            icon={<Clock className="h-3 w-3" />}
            label="Time span"
            value={spanLabel ?? '-'}
            sub={
              scope.earliest && scope.latest
                ? `${scope.earliest.toLocaleDateString()} → ${scope.latest.toLocaleDateString()}`
                : 'no timestamps recorded'
            }
          />
        </div>

        {/* Plain-English narration of the chain */}
        <p className="text-xs text-muted-foreground leading-relaxed">
          The selected file
          {rootFile?.filename && (
            <> <span className="font-mono text-foreground/80">{rootFile.filename}</span></>
          )}
          {rootFile?.partner && (
            <> was produced by <span style={{ color: rootFile.partner.color }}>{rootFile.partner.code}</span></>
          )}
          {rootFile?.iterationDisplayId && (
            <> in iteration <span className="font-mono">{rootFile.iterationDisplayId}</span></>
          )}.
          {' '}This lineage chain spans <span className="text-foreground/80">{scope.iterationCount}</span> iteration{scope.iterationCount === 1 ? '' : 's'}
          {' '}across <span className="text-foreground/80">{scope.partners.length}</span> partner{scope.partners.length === 1 ? '' : 's'}
          {scope.partners.length > 0 && (
            <>
              {' ('}
              {scope.partners.map((p, i) => (
                <span key={p.id}>
                  {i > 0 && ', '}
                  <span style={{ color: p.color }}>{p.code}</span>
                </span>
              ))}
              {')'}
            </>
          )}
          {spanLabel && <> over a span of <span className="text-foreground/80">{spanLabel}</span></>}.
          {scope.iterationCount > 3 && viewMode === 'files' && (
            <> When many iterations are involved, switching to <span className="text-foreground/80">Group by iteration</span> below makes the chain easier to read.</>
          )}
        </p>

        {/* View mode toggle */}
        <div className="flex items-center gap-2 pt-1 border-t border-border/40">
          <span className="text-[10px] uppercase tracking-wide text-muted-foreground">View</span>
          <div className="inline-flex rounded-md border border-border bg-muted/30 overflow-hidden">
            <button
              type="button"
              onClick={() => onViewModeChange('files')}
              className={cn(
                'px-2.5 py-1 text-[11px] inline-flex items-center gap-1 transition',
                viewMode === 'files' ? 'bg-blue-500/20 text-blue-200' : 'text-muted-foreground hover:text-foreground',
              )}
              title="One node per file - full detail"
            >
              <FileText className="h-3 w-3" /> Files
            </button>
            <button
              type="button"
              onClick={() => onViewModeChange('iterations')}
              className={cn(
                'px-2.5 py-1 text-[11px] inline-flex items-center gap-1 transition border-l border-border',
                viewMode === 'iterations' ? 'bg-blue-500/20 text-blue-200' : 'text-muted-foreground hover:text-foreground',
              )}
              title="One node per iteration - collapsed, good for big chains"
            >
              <Layers className="h-3 w-3" /> Group by iteration
            </button>
          </div>
          <span className="text-[10px] text-muted-foreground">
            {viewMode === 'files'
              ? `${graph.nodes.length} file node${graph.nodes.length === 1 ? '' : 's'} on screen`
              : `${scope.iterationCount} iteration node${scope.iterationCount === 1 ? '' : 's'} on screen`}
          </span>
        </div>
      </CardContent>
    </Card>
  )
}

function SummaryStat({
  icon,
  label,
  value,
  sub,
}: {
  icon: React.ReactNode
  label: string
  value: string
  sub: string
}) {
  return (
    <div className="space-y-0.5">
      <div className="inline-flex items-center gap-1 text-[10px] uppercase tracking-wide text-muted-foreground">
        {icon} {label}
      </div>
      <div className="text-xl font-semibold tabular-nums">{value}</div>
      <div className="text-[10px] text-muted-foreground truncate" title={sub}>{sub}</div>
    </div>
  )
}

function fmtSpan(ms: number): string {
  const sec = Math.floor(ms / 1000)
  const min = Math.floor(sec / 60)
  const hr = Math.floor(min / 60)
  const day = Math.floor(hr / 24)
  if (day >= 1) return `${day}d ${hr % 24}h`
  if (hr >= 1) return `${hr}h ${min % 60}m`
  if (min >= 1) return `${min}m`
  return `${sec}s`
}

// ─── Side panel - File mode ──────────────────────────────────────────────────

interface SelectedPanelProps {
  file: LineageFile
  depth: number
  isRoot: boolean
  incoming: LineageEdgeRaw[]
  outgoing: LineageEdgeRaw[]
  navigate: ReturnType<typeof useNavigate>
  clearSelection: () => void
  allNodes: LineageFile[]
}

function SelectedPanel({ file, depth, isRoot, incoming, outgoing, navigate, clearSelection, allNodes }: SelectedPanelProps) {
  const cls = CLASS_COLORS[file.classification ?? 'INTERNAL'] ?? CLASS_COLORS.INTERNAL
  const nodeMap = useMemo(() => new Map(allNodes.map((n) => [n.id, n])), [allNodes])
  const dl = useDownloadOrRequest()
  const authUser = useAuthStore((s) => s.user)
  const accessCtx = {
    role: authUser?.role,
    partnerName: authUser?.partner?.name ?? null,
    classification: file.classification ?? 'INTERNAL',
    sourceNodeId: file.nodeSourceId,
    outputId: file.nodeOutputId ?? null,
  }

  return (
    <div className="space-y-3">
      <div className="flex items-start justify-between gap-2">
        <h3 className="text-xs font-semibold flex items-center gap-1.5 min-w-0">
          <FileText className="h-3.5 w-3.5 text-muted-foreground shrink-0" aria-hidden="true" />
          <span className="truncate" title={file.filename}>{file.filename}</span>
        </h3>
        {!isRoot && (
          <button
            onClick={clearSelection}
            className="text-muted-foreground hover:text-foreground"
            title="Back to root"
          >
            <X className="h-3.5 w-3.5" />
          </button>
        )}
      </div>

      {/* Iteration context strip - front-and-centre so the cross-iteration
          story is the first thing the reader sees in the panel. */}
      <div
        className="rounded-md border p-2 text-[11px] space-y-1"
        style={{
          borderColor: file.partner ? `${file.partner.color}66` : 'rgba(100,116,139,0.35)',
          background: file.partner ? `${file.partner.color}14` : 'rgba(100,116,139,0.08)',
        }}
      >
        <div className="flex items-center gap-1.5">
          <PlayCircle className="h-3 w-3" style={{ color: file.partner?.color ?? '#94a3b8' }} />
          <span className="font-mono font-medium" title={file.iterationId}>
            {file.iterationDisplayId ?? file.iterationId.slice(0, 8) + '…'}
          </span>
          {file.iterationStatus && (
            <Badge variant="outline" className="text-[9px] h-3.5 px-1 leading-none">{file.iterationStatus}</Badge>
          )}
        </div>
        {file.iterationMachineName && (
          <p className="text-[10px] text-muted-foreground truncate">{file.iterationMachineName}</p>
        )}
        {file.partner && (
          <p className="text-[10px]">
            <span className="text-muted-foreground">Partner: </span>
            <span style={{ color: file.partner.color }}>{file.partner.fullName} ({file.partner.code})</span>
          </p>
        )}
        {file.iterationCreatedAt && (
          <p className="text-[10px] text-muted-foreground">
            Run started {new Date(file.iterationCreatedAt).toLocaleString()}
          </p>
        )}
      </div>

      <UsagesList file={file} navigate={navigate} />

      <div className="flex items-center gap-1.5 flex-wrap">
        <span className={cn('text-[9px] font-semibold uppercase tracking-wide rounded px-1.5 py-0.5 border', cls.bg, cls.text, cls.border)}>
          <Lock className="h-2.5 w-2.5 inline mr-0.5" /> {file.classification ?? 'INTERNAL'}
        </span>
        {isRoot && <Badge variant="outline" className="text-[9px] border-blue-500/50 text-blue-300">root</Badge>}
        {!isRoot && depth !== 0 && (
          <Badge variant="outline" className="text-[9px]">
            {depth > 0 ? `downstream d${depth}` : `upstream d${Math.abs(depth)}`}
          </Badge>
        )}
      </div>

      <dl className="text-[11px] space-y-1.5">
        <KvRow label="ID" value={<code className="font-mono break-all">{file.id}</code>} />
        {file.contentHash && (
          <KvRow
            label="SHA-256"
            value={
              <code className="font-mono text-[10px] break-all" title={file.contentHash}>
                {file.contentHash.slice(0, 16)}…
              </code>
            }
            icon={<Hash className="h-2.5 w-2.5" />}
          />
        )}
        {typeof file.sizeBytes === 'number' && (
          <KvRow label="Size" value={<span className="tabular-nums">{(file.sizeBytes / 1024).toFixed(1)} KB</span>} />
        )}
        {file.contentType && (
          <KvRow label="Content-Type" value={<code className="font-mono text-[10px]">{file.contentType}</code>} />
        )}
        {file.timestamp && (
          <KvRow
            label="Uploaded"
            value={<span className="tabular-nums">{new Date(file.timestamp).toLocaleString()}</span>}
            icon={<Clock className="h-2.5 w-2.5" />}
          />
        )}
        {file.uploadType && (
          <KvRow label="Upload type" value={<Badge variant="outline" className="text-[9px]">{file.uploadType}</Badge>} />
        )}
        {file.nodeSourceLabel && (
          <KvRow
            label="Produced by node"
            value={<span className="font-mono">{file.nodeSourceLabel}</span>}
          />
        )}
        {file.nodeOutputId && (
          <KvRow label="Output slot" value={<code className="font-mono text-[10px]">{file.nodeOutputId}</code>} />
        )}
      </dl>

      <div className="flex flex-wrap gap-1.5">
        {file.iterationId && (
          <Button asChild size="sm" variant="outline" className="h-7 text-[11px]">
            <Link to={`/iteration/${file.iterationId}`}>
              <ExternalLink className="h-3 w-3 mr-1" /> Open iteration
            </Link>
          </Button>
        )}
        <FileDownloadButton
          {...accessCtx}
          fileId={file.id}
          filename={file.filename}
          variant="muted"
          className="h-7 text-[11px] px-2.5 py-0 rounded-md border border-border/60 bg-background hover:bg-accent/50"
          onRequest={(fid, fname) => dl.openRequest(fid, fname)}
          onProbe={(fid, fname) => dl.tryDownload(fid, fname)}
        />
      </div>

      <RequestAccessDialog
        open={dl.state.kind === 'forbidden' || dl.state.kind === 'submitting' || dl.state.kind === 'submitted'}
        filename={file.filename}
        fileId={file.id}
        submitting={dl.state.kind === 'submitting'}
        submitted={dl.state.kind === 'submitted' ? { status: dl.state.status } : null}
        errorMessage={dl.state.kind === 'error' ? dl.state.message : null}
        onSubmit={(reason) => dl.submitRequest(file.id, reason)}
        onDownload={(fid) => { window.open(api.files.downloadUrl(fid), '_blank') }}
        onClose={dl.dismiss}
      />

      {incoming.length > 0 && (
        <div>
          <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1">
            Derived from ({incoming.length})
          </p>
          <ul className="space-y-0.5">
            {incoming.map((e) => {
              const src = nodeMap.get(e.source)
              return (
                <li key={e.id} className="text-[10px] flex items-center gap-1">
                  <ArrowLeft className="h-2.5 w-2.5 text-red-400 shrink-0" />
                  <button
                    type="button"
                    className="font-mono truncate hover:text-foreground text-muted-foreground text-left flex-1"
                    onClick={() => navigate(`/lineage/${e.source}`)}
                    title={src?.filename}
                  >
                    {src?.filename ?? e.source.slice(0, 12) + '…'}
                  </button>
                  {src?.partner && (
                    <span
                      className="text-[8px] shrink-0"
                      style={{ color: src.partner.color }}
                      title={`${src.partner.fullName} · ${src.iterationDisplayId ?? src.iterationId}`}
                    >
                      {src.partner.code}
                    </span>
                  )}
                </li>
              )
            })}
          </ul>
        </div>
      )}

      {outgoing.length > 0 && (
        <div>
          <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1">
            Used in derivation of ({outgoing.length})
          </p>
          <ul className="space-y-0.5">
            {outgoing.map((e) => {
              const tgt = nodeMap.get(e.target)
              return (
                <li key={e.id} className="text-[10px] flex items-center gap-1">
                  <ArrowRight className="h-2.5 w-2.5 text-emerald-400 shrink-0" />
                  <button
                    type="button"
                    className="font-mono truncate hover:text-foreground text-muted-foreground text-left flex-1"
                    onClick={() => navigate(`/lineage/${e.target}`)}
                    title={tgt?.filename}
                  >
                    {tgt?.filename ?? e.target.slice(0, 12) + '…'}
                  </button>
                  {tgt?.partner && (
                    <span
                      className="text-[8px] shrink-0"
                      style={{ color: tgt.partner.color }}
                      title={`${tgt.partner.fullName} · ${tgt.iterationDisplayId ?? tgt.iterationId}`}
                    >
                      {tgt.partner.code}
                    </span>
                  )}
                </li>
              )
            })}
          </ul>
        </div>
      )}

      {incoming.length === 0 && outgoing.length === 0 && (
        <p className="text-[10px] text-muted-foreground italic">
          No lineage edges on this file. It's either a workflow origin (TRIGGER output) or a leaf - or
          edges haven't been recorded yet (try "Rebuild lineage" on the iteration page).
        </p>
      )}
    </div>
  )
}

// ─── Side panel - Iteration mode ─────────────────────────────────────────────

function IterationPanel({
  group,
  isRootGroup,
  onPickFile,
  navigate,
}: {
  group: IterationGroup
  isRootGroup: boolean
  onPickFile: (fileId: string) => void
  navigate: ReturnType<typeof useNavigate>
}) {
  return (
    <div className="space-y-3">
      <div className="space-y-1">
        <div className="flex items-center gap-1.5">
          <PlayCircle className="h-3.5 w-3.5" style={{ color: group.partners[0]?.color ?? '#94a3b8' }} />
          <span className="text-xs font-mono font-semibold">
            {group.iterationDisplayId ?? group.iterationId.slice(0, 8) + '…'}
          </span>
          {isRootGroup && <Badge variant="outline" className="text-[9px] border-blue-500/50 text-blue-300">root</Badge>}
        </div>
        {group.iterationMachineName && (
          <p className="text-[11px] text-muted-foreground">{group.iterationMachineName}</p>
        )}
        {group.iterationStatus && (
          <Badge variant="outline" className="text-[9px]">{group.iterationStatus}</Badge>
        )}
      </div>

      {group.partners.length > 0 && (
        <div className="flex items-center gap-1 flex-wrap">
          {group.partners.map((p) => (
            <span
              key={p.id}
              className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[10px] border"
              style={{ background: `${p.color}14`, borderColor: `${p.color}55`, color: p.color }}
              title={p.fullName}
            >
              <span className="inline-block w-1.5 h-1.5 rounded-full" style={{ background: p.color }} />
              {p.code}
            </span>
          ))}
        </div>
      )}

      <div className="flex flex-wrap gap-1.5">
        <Button asChild size="sm" variant="outline" className="h-7 text-[11px]">
          <Link to={`/iteration/${group.iterationId}`}>
            <ExternalLink className="h-3 w-3 mr-1" /> Open iteration
          </Link>
        </Button>
        <Button
          size="sm"
          variant="outline"
          className="h-7 text-[11px]"
          onClick={() => navigate(`/provenance/iteration/${group.iterationId}`)}
        >
          <GitBranch className="h-3 w-3 mr-1" /> Open provenance
        </Button>
      </div>

      {group.files.length > 0 && (
        <div>
          <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1">
            Produced in this iteration ({group.files.length})
          </p>
          <ul className="space-y-0.5">
            {group.files.map((f) => (
              <li key={f.id} className="text-[11px] flex items-center gap-1.5">
                <FileText className="h-3 w-3 text-muted-foreground shrink-0" />
                <button
                  type="button"
                  className="font-mono truncate hover:text-foreground text-muted-foreground text-left flex-1"
                  onClick={() => onPickFile(f.id)}
                  title={f.filename}
                >
                  {f.filename}
                </button>
                <span
                  className={cn(
                    'text-[8px] font-semibold uppercase tracking-wide rounded px-1 py-0 border shrink-0',
                    CLASS_COLORS[f.classification ?? 'INTERNAL']?.bg,
                    CLASS_COLORS[f.classification ?? 'INTERNAL']?.text,
                    CLASS_COLORS[f.classification ?? 'INTERNAL']?.border,
                  )}
                >
                  {f.classification ?? 'INTERNAL'}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {group.referencedFiles.length > 0 && (
        <div>
          <p className="text-[10px] uppercase tracking-wider text-amber-300/80 mb-1 inline-flex items-center gap-1">
            <ArrowLeft className="h-2.5 w-2.5" /> Used as input from other iterations ({group.referencedFiles.length})
          </p>
          <ul className="space-y-0.5">
            {group.referencedFiles.map((f) => (
              <li key={f.id} className="text-[11px] flex items-center gap-1.5">
                <FileText className="h-3 w-3 text-muted-foreground shrink-0" />
                <button
                  type="button"
                  className="font-mono truncate hover:text-foreground text-muted-foreground text-left flex-1"
                  onClick={() => onPickFile(f.id)}
                  title={f.filename}
                >
                  {f.filename}
                </button>
                {f.iterationDisplayId && (
                  <span
                    className="text-[8px] font-mono shrink-0 text-muted-foreground"
                    title={`Produced in ${f.iterationDisplayId}`}
                  >
                    ← {f.iterationDisplayId}
                  </span>
                )}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

/**
 * Cross-iteration usages list. Groups OUTPUT + INPUT refs by iteration so the
 * reader sees one row per (iteration, role) pair - answers "this file is
 * produced in iteration A and used as input in iterations B and C".
 */
function UsagesList({
  file,
  navigate,
}: {
  file: LineageFile
  navigate: ReturnType<typeof useNavigate>
}) {
  const grouped = useMemo(() => {
    type Row = {
      iterationId: string
      iterationDisplayId: string | null
      iterationStatus: string | null
      role: LineageUsage['role']
      nodes: Array<{ nodeId: string; nodeLabel: string | null; inputId: string | null; outputId: string | null }>
    }
    const byKey = new Map<string, Row>()
    for (const u of file.usages) {
      const key = `${u.iterationId}|${u.role}`
      const row =
        byKey.get(key) ??
        ({
          iterationId: u.iterationId,
          iterationDisplayId: u.iterationDisplayId,
          iterationStatus: u.iterationStatus,
          role: u.role,
          nodes: [],
        } satisfies Row)
      row.nodes.push({
        nodeId: u.nodeId,
        nodeLabel: u.nodeLabel,
        inputId: u.inputId,
        outputId: u.outputId,
      })
      byKey.set(key, row)
    }
    // OUTPUT rows first, then INPUT rows; producing iteration first within each role.
    return Array.from(byKey.values()).sort((a, b) => {
      if (a.role !== b.role) return a.role === 'OUTPUT' ? -1 : 1
      if (a.iterationId === file.iterationId) return -1
      if (b.iterationId === file.iterationId) return 1
      return (a.iterationDisplayId ?? a.iterationId).localeCompare(b.iterationDisplayId ?? b.iterationId)
    })
  }, [file])

  if (grouped.length === 0) return null

  const otherIterationCount = new Set(
    file.usages.map((u) => u.iterationId).filter((id) => id !== file.iterationId),
  ).size

  return (
    <div>
      <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1 inline-flex items-center gap-1">
        <PlayCircle className="h-2.5 w-2.5" />
        Used in iterations ({new Set(file.usages.map((u) => u.iterationId)).size})
        {otherIterationCount > 0 && (
          <span className="text-amber-300 normal-case font-normal">
            · {otherIterationCount} beyond the one that produced it
          </span>
        )}
      </p>
      <ul className="space-y-1">
        {grouped.map((row) => {
          const isOwn = row.iterationId === file.iterationId
          return (
            <li
              key={`${row.iterationId}-${row.role}`}
              className="rounded border border-border/60 bg-muted/20 px-2 py-1.5 text-[10px] space-y-0.5"
            >
              <div className="flex items-center justify-between gap-2">
                <button
                  type="button"
                  onClick={() => navigate(`/iteration/${row.iterationId}`)}
                  className="font-mono font-medium hover:text-foreground truncate text-left"
                  title={row.iterationId}
                >
                  {row.iterationDisplayId ?? row.iterationId.slice(0, 8) + '…'}
                </button>
                <span
                  className={cn(
                    'inline-flex items-center gap-0.5 px-1.5 py-0 rounded text-[9px] font-semibold uppercase tracking-wide border shrink-0',
                    row.role === 'OUTPUT'
                      ? 'bg-emerald-500/15 text-emerald-300 border-emerald-500/40'
                      : 'bg-blue-500/15 text-blue-300 border-blue-500/40',
                  )}
                >
                  {row.role === 'OUTPUT' ? (isOwn ? 'produced here' : 'produced') : 'used as input'}
                </span>
              </div>
              <div className="text-muted-foreground flex flex-wrap gap-x-2 gap-y-0.5">
                {row.nodes.map((n, i) => (
                  <span key={i} className="inline-flex items-center gap-0.5">
                    <span className="opacity-60">on</span>
                    <span className="font-mono">{n.nodeLabel ?? n.nodeId}</span>
                    {row.role === 'INPUT' && n.inputId && (
                      <span className="opacity-60">(slot {n.inputId})</span>
                    )}
                    {row.role === 'OUTPUT' && n.outputId && (
                      <span className="opacity-60">(slot {n.outputId})</span>
                    )}
                  </span>
                ))}
              </div>
              {row.iterationStatus && (
                <span className="inline-flex items-center text-[9px] text-muted-foreground/80">
                  {row.iterationStatus}
                </span>
              )}
            </li>
          )
        })}
      </ul>
    </div>
  )
}

function KvRow({ label, value, icon }: { label: string; value: React.ReactNode; icon?: React.ReactNode }) {
  return (
    <div className="flex items-start gap-2">
      <dt className="text-[9px] uppercase tracking-wider text-muted-foreground w-20 shrink-0 mt-0.5 inline-flex items-center gap-0.5">
        {icon}{label}
      </dt>
      <dd className="text-[10px] flex-1 min-w-0">{value}</dd>
    </div>
  )
}
